services:

  go-iiif:
    build:
      context: .
    command: /go/iiif-server -server-uri http://0.0.0.0:8080 -config-source file:///etc/iiif-server
    ports:
      - "6701:8080"
    working_dir: /go
    volumes:
      - ./cfg/etc/config.json:/etc/iiif-server/config.json
      - ./cfg/etc/instructions.json:/etc/iiif-server/instructions.json
    env_file:
      - .env
    